version: '2'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && export SECRET_KEY_BASE=`bundle exec rake secret` && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/kgcash
      - /cloudsql:/cloudsql
    ports:
      - "8080:8080"
    depends_on:
      - db
