# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box      = 'precise64'
	config.vm.box_url  = 'http://files.vagrantup.com/precise64.box'
	config.vm.network :private_network, ip: "192.168.78.79"
	config.vm.hostname = "kgcashlocal"
	config.vm.synced_folder "/Users/geordiehenderson/dev/heroku/kgcash", "/home/vagrant/kgcash", type: "nfs"

	config.vm.network :forwarded_port, guest: 3000, host: 3000

	config.vm.provider :virtualbox do |vb|
	  vb.customize ["modifyvm", :id, "--memory", 2048]
	  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	end

	config.vm.provision :ansible do |ansible|
		ansible.limit = 'all'
		ansible.playbook = "main.yml"
		# ansible.inventory_path = "inventories/vagrant"
		ansible.verbose = 'v'
	end
end
