# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project, GKE_EMAIL with the service account email, GKE_KEY with the service account key.
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER and IMAGE environment variables (below).

name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-west1-b
  GKE_CLUSTER: kgcash-2018-10
  IMAGE: kgcash

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
          
    steps:
    - name: Verify MySQL connection from host
      run: |
        mysql --host 127.0.0.1 --port ${{ job.services.db.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"
        mysql --host 127.0.0.1 --port ${{ job.services.db.ports[3306] }} -uroot -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';"
        mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --host 127.0.0.1 --port ${{ job.services.db.ports[3306] }} -uroot -proot mysql

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Cache latest Docker image to reduce build time
    - name: Build cache
      run: |
        docker pull gcr.io/"$GKE_PROJECT"/"$IMAGE":latest

    # Create tmp DB_CONFIG file for building into Docker container
    - name: Write database config file
      env:
        DB_CONFIG: ${{ secrets.DB_CONFIG }}
      run: |
        pwd
        echo "$DB_CONFIG" > ./config/database.yml

    # Build the Docker image
    - name: Build
      run: |
        docker build -t gcr.io/"$GKE_PROJECT"/"$IMAGE" --cache-from gcr.io/"$GKE_PROJECT"/"$IMAGE":latest .

    # Test
    - name: Test
      run: |
        docker run --net=host -e "RAILS_ENV=test" gcr.io/"$GKE_PROJECT"/"$IMAGE" 'rake db:create & rake db:migrate & rspec'

    # Remove DB Config file
    - name: Remove database config file
      run: |
        rm ./config/database.yml

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker -- push gcr.io/"$GKE_PROJECT"/"$IMAGE"

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        kubectl delete deployments --all
        kubectl create -f ./kubernetes/kgcash-2018-frontend.yaml
