# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project, GKE_EMAIL with the service account email, GKE_KEY with the service account key.
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER and IMAGE environment variables (below).

name: Build and Deploy to GKE

on:
  workflow_dispatch:

  push:
    branches:
    - main

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-west1-b
  GKE_CLUSTER: kgcash-2018-10
  IMAGE: kgcash
  # USE_GKE_GCLOUD_AUTH_PLUGIN: true

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
          
    steps:

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Export gcloud related env variable
      run: export CLOUDSDK_PYTHON="/usr/bin/python3"

    - name: Update GKE
      run: | 
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
        sudo apt-get update

    - name: Verify MySQL connection from host
      run: |
        mysql --host 127.0.0.1 --port ${{ job.services.db.ports[3306] }} -uroot -proot -e "SHOW GRANTS FOR 'root'@'localhost'"

    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: access_token
        workload_identity_provider: 'projects/567189324080/locations/global/workloadIdentityPools/kgcash-identity-pool-github/providers/kgcash-identity-provider'
        service_account: 'kgcash-github-actions@kgcash-176905.iam.gserviceaccount.com'

    - id: 'get-credentials'
      uses: google-github-actions/get-gke-credentials@v0.4.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Log in to GCR
      uses: docker/login-action@v3
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    # Create tmp DB_CONFIG file for building into Docker container
    - name: Write database config file
      env:
        DB_CONFIG: ${{ secrets.DB_CONFIG }}
      run: |
        pwd
        echo "$DB_CONFIG" > ./config/database.yml

    - name: Setup Docker buildx action
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    # Build the Docker image with caching
    - name: Build the Docker image using cache
      uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        tags: gcr.io/${{ env.GKE_PROJECT }}/${{ env.IMAGE }}:test

    # Test
    # docker run --rm gcr.io/${{ env.GKE_PROJECT }}/${{ env.IMAGE }}:test
    - name: Test
      run: |
        docker run --net=host -e "RAILS_ENV=test" gcr.io/${{ env.GKE_PROJECT }}/${{ env.IMAGE }}:test /bin/bash -c "rails db:create; rails db:migrate; rspec"

    # Push the Docker image to Google Container Registry 
    - name: Push the docker image go Google Artifact Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        provenance: false
        tags: gcr.io/${{ env.GKE_PROJECT }}/${{ env.IMAGE }}:latest

    # Remove DB Config file
    - name: Remove database config file
      run: |
        rm ./config/database.yml

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        kubectl delete deployments --all
        kubectl create -f ./kubernetes/kgcash-2018-frontend.yaml
